print("Title: The Last Bench")
print("Every afternoon, old Mr Ade sat on the same park bench under the large mango tree at Freedom Garden")
print("It was a quiet, away from the city's noise. He always had a book in hand,though he barely turned the pages anymore.")
print("He just stared into the distance, as if watching something everyone wasn't seeing")
print("Children played nearby. Couples walked hand in hand. But Mr Ade sat alone always.")
print("One day, a little girl named Kemi, about nine years of age, skipped over and sat beside him. She didn't say any word at first, just glanced at him with curiosity")
print("'You always sit here',she finally said. Mr Ade smiled faintly, 'Yes, I do', he said.")
print("'Why?'she asked, swinging her legs. He paused, then looked toward the garden's far end. 'Because this is where i fell in love.....many,many years ago.'")
print("Kemi's eyes widened, 'With your wife?' He nodded,'She used to meet here after work.We'd talk for hours,laugh about little things,and dream big dreams.'")
print("Kemi's eyes smiled, 'Where is she now?' Mr Ade looked down at the wedding band on his wrinkled finger. 'She passed away five years ago.Cancer.' ")
print("Kemi's smile faded, 'I'm sorry.' 'It's alright,' he said gently. The bench helps me remember the joy.The love never left.It just lives differently now.'")
print("From that day on,Kemi came to sit with him every afternoon.She brought sweets,stories from school, even a drawing of him and a woman holding hands on a bench")
print("One day, Mr Ade didn't show up. The next day, he didn't either. On the third day, a small brass plaque appeared on the bench. 'In loving memory of Mr Ade-who taught us that true love never dies")
print("Kemi came every afternoon after that, sitting quietly on the bench with a book in hand, staring into the distance. JUST LIKE HE USED TO") 